#!/bin/bash

#Initialization script for all types of LINUX OSes by VZlatkov (a.k.a. Xerxes).
#v1.0.1
#This is the extended variant of init.sh
#In this initial revision an if statement will be added that will determine which is the default OS package manager and use it to create the variable needed to execute all installations and updates.
#v1.0.2
#In this revision, the script will be amde interactive and would provide the options to install different components to the server.
#v1.0.3
#In this revision - fix the sudo issue by determine if the user is root or not.



#DECLARE COLORS
GREEN="\e[32m"
END="\e[0m"
cr=`echo $'\n'`
cr=${cr%.}
nl=`echo '>>>'`	

#Declaring the most common package managers! 
declare -a arr=("yum" "pakman" "apt")

#For loop that checks which is the correct one
for i in "${arr[@]}"; do
	echo which $i 1> /dev/null
done

echo '......................................................'
#This is an "if" statement to determine the package manager

if [ $? -eq 0 ]
then echo "The package in use is $i"
fi
echo '......................................................'

#The initialization starts from here


#Opening to the script. It is a function that would break if no further input is required.

installprompt(){

	read -p "Would you like to install a package? (y/n) $cr" would

}
	installprompt # Calls the installation prompt

#Function to repeat the installation or break	
	repeatinstall(){

        read -p "state the package name $cr $cr $nl" pkg #If the "yes" option is chosen, installs the package and then calls the install prompt once again

        sudo $i -y install $pkg
        installprompt

}


if [ $would == y ]
then
	
repeatinstall

else
sleep 3 
echo 'Script ends'
exit	
clear
fi

repeatinstall
